macro(add_exe exe_name)
	#project src files
	file(GLOB_RECURSE cpp_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
	file(GLOB_RECURSE h_files ${CMAKE_CURRENT_SOURCE_DIR}/*.h)
    if(USE_CUDA)
		file(GLOB_RECURSE cu_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cu)
		file(GLOB_RECURSE cuh_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cuh)
	else()
		set(cu_files "")
        set(cuh_files "")
    endif(USE_CUDA)
    list(APPEND src_files ${h_files} ${cpp_files} ${cu_files} ${cuh_files})
    message(STATUS "add exe " ${exe_name} " with files " ${src_files})
    add_executable(${exe_name} ${src_files})
endmacro()

macro(add_lib lib_name)
	#project src files
	file(GLOB_RECURSE cpp_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
	file(GLOB_RECURSE h_files ${CMAKE_CURRENT_SOURCE_DIR}/*.h)
    if(USE_CUDA)
		file(GLOB_RECURSE cu_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cu)
		file(GLOB_RECURSE cuh_files ${CMAKE_CURRENT_SOURCE_DIR}/*.cuh)
	else()
		set(cu_files "")
        set(cuh_files "")
    endif(USE_CUDA)
    list(APPEND src_files ${h_files} ${cpp_files} ${cu_files} ${cuh_files})
    message(STATUS "add library " ${lib_name} " with files " ${src_files})
    add_library(${lib_name} STATIC ${src_files})
endmacro()

function(rapidht_add_test TARGET_NAME SOURCES)
	set (EXTRA_ARGS ${ARGN})
    	list(LENGTH EXTRA_ARGS NUM_EXTRA_ARGS)
    	if (${NUM_EXTRA_ARGS} GREATER 0)
		list(GET EXTRA_ARGS 0 OPTIONAL_ARG)
		add_executable(${TARGET_NAME} ${SOURCES} ${OPTIONAL_ARG})
	else()
		add_executable(${TARGET_NAME} ${SOURCES})
	endif()
	
	target_link_libraries(${TARGET_NAME} gtest_main ${RAPIDHT_LIBRARIES})
	add_test(NAME ${TARGET_NAME} COMMAND ${TARGET_NAME})
	set_target_properties (${TARGET_NAME} PROPERTIES FOLDER "Tests")
endfunction()